print("         ___oooo")
print("       //   /    o")
print("     / /   |       o")
print("    | /   |___     o")
print("   | |    ___/    o ")
print("   | |   /   oooo    GOAL!")
print("  | /   |  _______________________ ")
print(" | |    | |_______________________| ")
print("||     |____\_/\_/\_/\/\//\/\/\/\/ ")
print("||     |    \ \/\/\/\/\/\/\/\/\/")
print("||     \     \ \/\/\/\/\/\/\/\/")
print("| |     |    |  \/\/\/\/\/\/\/")
print(" | |     |   |   \/\/\/\/\/\/")
print("  | |     \_/    |\/\/\/\/\/|")
print("   \ \      \    |\/\/\/\/\/| ")
print("    |         \ ")
print("    |          |")
print("    |          |")
print("    |          |")
print("    |          |")
print("     |         |")
print("     |_________| ")
print("      |_______|")
print("      |       |")
print("     ||         | ")
print("    | |          |")
print("   |  /          |")
print("  |  /          /")
print("  /\ |_________|")
print(" |   /       / ")
print(" |   |      /")
print(" |  |      |  ")
print("  \  |      \ ")
print("   \  |      \ ")
print("     \  \     |")
print("       \  \    |")
print("         \  \  |_")
print("           \\__/ \_")
print("             |     | ")
print("             |     / ")
print("             |    | ")
print("             |   / ")
print("             |__/ ")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("") 
print("")
print("")
print("")
print("")
print("")
print("")
print("")
